### ISSUE TITLE
Pass param in translated message

### ISSUE THREAD

**Issue by redplane** [XAMLMarkupExtensions/WPFLocalizationExtension#171]
Hi,

I have searched for solution to pass parameter into translated message.
Let say, I have a raw translate message with Key-Value in **resx** file defined like below:

**Key**: `MSG_GREETING`
**Value**: `Hello {{name}}`

I wonder are there any solutions to help me to pass a string to replace `{{name}}` placeholder in the translated message or not.

The expected result should be:

**Hello Adam**

**Comment by konne** [comment]
@SeriousM do you have an idea, I don't know currently a possibility

**Comment by xmedeko** [comment]
I do not know, what's the state of this feature now. (I do it in the code behind, too.)

There has been a few closed issues about this topic: #19, #65, #78 
Also see this [SO question](https://stackoverflow.com/questions/9520030).

**Comment by konne** [comment]
@xmedeko @SeriousM do you think to add this as a Feature Request?
I like to make a new FR on that topic.

**Comment by xmedeko** [comment]
I am not sure, I need this rarely, and even try to avoid it. Why? Because of easier resource translation management.

E.g. if I make a resource like: `Your have been born on {0}.` then 1. the translator can make a mistake e.g. forget `}` 2. translator can move words like `{0} is your birthday.` (in another language) which may change the intended visual design of the text.  So, I rather make text `Your birthday:` and add a value by a separate `TextBlock`. (When I need a word wrapping, I use one `TextBlock` with more `Run` elements.)

And yes, I need the string formatting rarely anyway. But for these rare cases, a new property in a MVVM model is OK for me. I understand some people use this more often.

I think it would be good to mention in doc (`README.md`) that WPFLocalizationExtension cannot do string formatting and maybe add the FR to it if you make one.

**Comment by SeriousM** [comment]
You could create an inheritance of the provider and manipulate the string
afterwards.

**Comment by konne** [comment]
@xmedeko I fully understand your arguments, but i18n like in angular even support pluralisation,..
https://angular.io/guide/i18n So I see the need.

**Comment by mihaicupsuite** [comment]
This should work:

key1 =  Hello {{0}}
<TextBlock Text="{Binding Name, StringFormat={lex:LocText key1}}" />

**Comment by konne** [comment]
@mihaicupsuite this should give an error instantly if you change the lang. because Binding don't allow that any "Param" is changed after the binding is ready.

**Comment by konne** [comment]
I will close this issue and please follow up the discussion here:  #171
