### ISSUE TITLE
x64 design xaml issue

### ISSUE THREAD

**Issue by GrazianoDeKa** [XAMLMarkupExtensions/WPFLocalizationExtension#217]
Hi all,
first of all I'd like to thank you for the very great and useful job. I have to bring to your attention an issue concerning the xaml and the design view of VS. If the solution/project is compiled with AnyCPU, in design mode I see the keys used in {lex:Loc KEY}, even the default value or just Key:KEY. If I compile the solution/project with x64, everything disappears and I don't see nothing in design mode, not the default value nor the Key:KEY (for example a button with just a text as Content becomes completely collapsed), even if in runtime is working correctly. 
This is not a blocking stuff but during the design of windows/controls it is quite helpful to see the final appearance, as you can easly imagine.
Is there something I am missing?
Thanks in advance

**Comment by konne** [comment]
@GrazianoDeKa thanks for the finding. The issue is that the design mode is tricky. If you can debug that issue a little bit more this would be great.

**Comment by luislhg** [comment]
That is because the visual studio design instance only works in x86 (or Any CPU, in that case the VS instance will opt for the x86 version). This is not the extension's fault. If you have IoC or other stuffs that bind and reflect in design time you will notice the same effect, nothing will change/reflect in design-time if running on x64.

Bottom-line: Always set your application to Any CPU, this way VS will always use internally the x86 version for its design instance, and in runtime it will always run in x64 anyway if your PC is x64.
(Just make sure the checkbox "Prefer 32-bit" is NOT checked. This is available in Project -> Build tab)

You can see numerous questions about this: https://stackoverflow.com/questions/5378919/visual-studio-designer-in-x64-doesnt-work
